#define WIDTH_EASY 20
#define HEIGHT_EASY 10
#define FLAG_COUNT_EASY 6
#define DEFAULT_PLAYER_X_EASY 1
#define DEFAULT_PLAYER_Y_EASY HEIGHT_EASY - 2
#define KEY_STANDARD_EASY 3
#define TIME_STANDARD_EASY 200

#define WIDTH_NORMAL 30
#define HEIGHT_NORMAL 15
#define FLAG_COUNT_NORMAL 9
#define DEFAULT_PLAYER_X_NORMAL 1
#define DEFAULT_PLAYER_Y_NORMAL HEIGHT_NORMAL - 2
#define KEY_STANDARD_NORMAL 5
#define TIME_STANDARD_NORMAL 300

#define WIDTH_HARD 40
#define HEIGHT_HARD 20
#define FLAG_COUNT_HARD 12
#define DEFAULT_PLAYER_X_HARD 1
#define DEFAULT_PLAYER_Y_HARD HEIGHT_HARD - 2
#define KEY_STANDARD_HARD 7
#define TIME_STANDARD_HARD 400

#define STAGE_WALL "#"
#define FLAG "▶"
#define PLAYER "◆"

#define FIRST_CLEAR_REWARD 100

// dud
#define DUD_SECONDS 5

// pressKey
#define HIT_COUNT 0
#define TARGET_GOAL 50
#define GAME_DURATION 10

//typingPractice
#define NUM_SENTENCES 8
#define MAX_LENGTH 100
#define TIME_LIMIT 10.0 
